version: '3.0'

services:

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - USE_SINGLE_REGION=1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,s3
    ports:
      - '4566:4566'