spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  liquibase:
    change-log: classpath:/db/changelog/db.tracking-service.xml
cloud:
  aws:
    stack.auto: false
    region:
      static: us-east-1
      
aws:
  sqs:
    serviceEndpoint: http://localhost:4566
    signingRegion: eu-central-1
    accessKey: foo
    secretKey: bar