spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  liquibase:
    change-log: classpath:/db/changelog/db.tracking-service.xml
cloud:
  aws:
    stack.auto: false
    region:
      static: eu-central-1
      
aws:
  sqs:
    serviceEndpoint: http://localhost:4566
    signingRegion: eu-central-1
    accessKey: foo
    secretKey: bar
    
blip:
  url: http://localhost:2345/
    
discord:
  channelId: 980498952946339890
  inviteLink: https://discord.com/api/oauth2/authorize?client_id=979739306866393148&permissions=380104621072&scope=applications.commands%20bot
  
logging:
  level:
    br.com.claro.whatsapp.tracking.blip.BlipClient: DEBUG  